// Automatically generated by Gradle - DO NOT MODIFY
package frc.robot;

public final class BuildConstants {
  public static final String MAVEN_GROUP = "";
  public static final String MAVEN_NAME = "Mk5n-otonom";
  public static final String VERSION = "unspecified";
  public static final int GIT_REVISION = 1;
  public static final String GIT_SHA = "84a119b121a8e99463fff959bcdad6ee8fe96231";
  public static final String GIT_DATE = "2026-02-23 11:28:28";
  public static final String GIT_BRANCH = "main";
  public static final String BUILD_DATE = "2026-02-23 11:28:28";
  public static final boolean DIRTY = false;

  private BuildConstants(){}
}
