// Automatically generated by Gradle - DO NOT MODIFY
package frc.robot;

public final class BuildConstants {
  public static final String MAVEN_GROUP = "";
  public static final String MAVEN_NAME = "Mk5n-otonom";
  public static final String VERSION = "unspecified";
  public static final int GIT_REVISION = 1;
  public static final String GIT_SHA = "184f16e8fe7962e676f4daa85b630622a327afae";
  public static final String GIT_DATE = "2026-03-21 14:12:16";
  public static final String GIT_BRANCH = "main";
  public static final String BUILD_DATE = "2026-03-21 14:12:16";
  public static final boolean DIRTY = false;

  private BuildConstants(){}
}
